user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /

location:
    resource: "@LocationBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
