location:
    resource: "@LocationBundle/Controller/"
    type: annotation

user:
    resource: "@UserBundle/Controller/"
    type: annotation

payment:
    resource: "@PaymentBundle/Controller/"
    type: annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
