services:
#    payment.example:
#        class: PaymentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  payment_listener:
        class: PaymentBundle\EventListener\PaymentListener
        arguments: ["@mailer", "@router", "%mailer_user%"]
        tags:
          - { name: doctrine.event_listener, event: postPersist }
